name: Run the tests against a Grist instance

on:
  push:
    branches:
      - main
    paths:
      - grist-deployment-tests/
  pull_request:
    branches:
      - main
    paths:
      - grist-deployment-tests/
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run the tests on
        type: choice
        options:
          - tests preprod
          - tests latest
        default: tests latest
  schedule:
    - cron: 0 8 * * *

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || "tests latest" }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        cd grist-deployment-tests
        npm install

    - name: Run the API tests
      shell: bash
      env:
        GRIST_DOMAIN: ${{ vars.GRIST_DOMAIN }}
        USER_API_KEY: ${{ secrets.USER_API_KEY }}

      run: |
        cd grist-deployment-tests
        npm run test:api

    - name: Run the e2e tests
      shell: bash
      env:
        GRIST_DOMAIN: ${{ vars.GRIST_DOMAIN }}

      run: |
        cd grist-deployment-tests
        npm run test:e2e:ci
